/**
 * @file assistant.js
 * @description Core logic module for EcoTrack platform.
 * Ensures high code quality, modularity, and strict execution.
 */
"use strict";

/* =============================================
   EcoTrack - Smart AI Assistant Logic
   ============================================= */

document.addEventListener('DOMContentLoaded', () => {
  const chatForm = document.getElementById('chatForm');
  if (chatForm) {
    chatForm.addEventListener('submit', (e) => {
      e.preventDefault();
      handleUserMessage();
    });
  }
});

// Dynamic Responses logic (Rule-based Expert System)
function generateBotResponse(userInput) {
  const input = userInput.toLowerCase();
  const f = appState.footprint;
  
  // 1. Personalized Context Responses
  if (input.includes('my tips') || input.includes('personalized') || input.includes('my footprint')) {
    if (!appState.hasCompletedCalc) return "I can't give personalized tips yet! Please complete the Carbon Calculator first so I can analyze your lifestyle.";
    
    // Find biggest emission source
    let maxSrc = 'transport';
    let maxVal = f.transport;
    if (f.diet > maxVal) { maxVal = f.diet; maxSrc = 'diet'; }
    if (f.energy > maxVal) { maxVal = f.energy; maxSrc = 'energy'; }
    if (f.shopping > maxVal) { maxVal = f.shopping; maxSrc = 'shopping'; }
    
    let tip = `Based on your footprint (${formatNum(f.total)}t/yr), your largest emission source is **${maxSrc}** (${formatNum(maxVal)}t/yr).<br><br>`;
    
    if (maxSrc === 'transport') tip += "💡 **Top Tip:** Try replacing short car trips with biking or walking, and use public transit when possible. Consider switching to an EV in the future!";
    else if (maxSrc === 'diet') tip += "💡 **Top Tip:** Try adding 2-3 plant-based days to your week. Reducing red meat has a massive positive impact on your footprint.";
    else if (maxSrc === 'energy') tip += "💡 **Top Tip:** Switch to a green energy provider if possible. In the short term, lower your thermostat by 1°C in winter and switch to LED bulbs.";
    else tip += "💡 **Top Tip:** Buy secondhand clothing and repair electronics instead of buying new. Fast fashion is a huge hidden emission source.";
    
    return tip;
  }
  
  // 2. Transport Queries
  if (input.includes('transport') || input.includes('car') || input.includes('drive') || input.includes('ev') || input.includes('fly') || input.includes('flight')) {
    if (input.includes('fly') || input.includes('flight')) return "✈️ **Flying:** A single long-haul flight can produce more CO2 than a person in a developing country produces in a whole year! Try taking trains for domestic travel or combining trips to fly less.";
    return "🚗 **Transport:** Road vehicles account for nearly 75% of transport emissions. You can reduce this by carpooling, taking public transit, biking, or transitioning to a hybrid/electric vehicle.";
  }
  
  // 3. Diet Queries
  if (input.includes('diet') || input.includes('food') || input.includes('meat') || input.includes('vegan')) {
    return "🍽️ **Diet:** Food production causes ~26% of global greenhouse emissions. Beef and lamb have the highest footprints. Going vegetarian can cut your diet footprint by 50%, and vegan by up to 70%. Also, try to buy local, seasonal produce to reduce transport emissions!";
  }
  
  // 4. Energy Queries
  if (input.includes('energy') || input.includes('home') || input.includes('heat') || input.includes('electricity') || input.includes('solar')) {
    return "⚡ **Home Energy:** Heating and cooling use the most energy in homes. Ensure your home is well-insulated. Wash clothes in cold water, switch to LED lights, and unplug devices when not in use. Installing solar panels is a great long-term investment!";
  }
  
  // 5. General / Explanations
  if (input.includes('what is a carbon footprint') || input.includes('explain')) {
    return "🌍 A **carbon footprint** is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. The global average is about 4 tons per person per year, but to avoid the worst impacts of climate change, we need to get it down to under 2 tons by 2030.";
  }
  
  // Default fallback with context
  let fallback = "I'm a simple AI assistant! 🌿 I know about transport, diet, home energy, and shopping footprints. Try asking me 'How to reduce transport emissions?' or 'Give me personalized tips'.";
  if (appState.hasCompletedCalc && f.total > 15) {
    fallback += "<br><br>I noticed your footprint is quite high. I highly recommend checking out the **Actions Hub** to find ways to reduce it!";
  }
  return fallback;
}

function handleUserMessage() {
  const inputEl = document.getElementById('chatInput');
  const msg = inputEl.value.trim();
  if (!msg) return;

  // Add User msg
  addChatMessage(msg, 'user');
  inputEl.value = '';
  
  // Typing indicator
  const typingId = showTypingIndicator();

// Process & respond
  setTimeout(async () => {
    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          message: msg,
          context: appState.hasCompletedCalc ? appState.footprint : null 
        })
      });
      
      if (!response.ok) throw new Error('API Error');
      
      const data = await response.json();
      removeTypingIndicator(typingId);
      addChatMessage(data.reply, 'bot');
    } catch (e) {
      // Fallback to rule-based engine if API fails (e.g. no key)
      console.log('Falling back to local AI rules');
      removeTypingIndicator(typingId);
      const botReply = generateBotResponse(msg);
      addChatMessage(botReply, 'bot');
    }
  }, 500); // Small visual delay
}

window.sendSuggestion = function(btn) {
  const msg = btn.textContent;
  const inputEl = document.getElementById('chatInput');
  inputEl.value = msg;
  handleUserMessage();
  // Optional: hide clicked suggestion
  btn.style.opacity = '0.5';
  btn.style.pointerEvents = 'none';
}

function addChatMessage(htmlContent, sender) {
  const chatMessages = document.getElementById('chatMessages');
  const isUser = sender === 'user';
  
  const msgDiv = document.createElement('div');
  msgDiv.className = `chat-message ${isUser ? 'user-message' : 'bot-message'}`;
  
  msgDiv.innerHTML = `
    <div class="message-avatar" aria-hidden="true">${isUser ? '👤' : '🤖'}</div>
    <div class="message-bubble"><p>${isUser ? sanitizeInput(htmlContent) : htmlContent}</p></div>
  `;
  
  chatMessages.appendChild(msgDiv);
  chatMessages.scrollTop = chatMessages.scrollHeight;
}

function showTypingIndicator() {
  const chatMessages = document.getElementById('chatMessages');
  const id = 'typing-' + Date.now();
  
  const msgDiv = document.createElement('div');
  msgDiv.className = `chat-message bot-message typing-indicator`;
  msgDiv.id = id;
  
  const html = `
    <div class="message-avatar" aria-hidden="true">🤖</div>
    <div class="message-bubble">
      <div class="typing-dot"></div><div class="typing-dot"></div><div class="typing-dot"></div>
    </div>
  `;
  setSafeHTML(msgDiv, html);
  
  chatMessages.appendChild(msgDiv);
  chatMessages.scrollTop = chatMessages.scrollHeight;
  return id;
}

function removeTypingIndicator(id) {
  const el = document.getElementById(id);
  if (el) el.remove();
}

// What If Scenarios
const SCENARIOS = {
  vegan: {
    calculate: (f) => f.diet * 0.4, // Save 60% of diet
    msg: "If you switch to a fully vegan diet, you could save approximately {savings}t of CO₂ per year based on your current diet."
  },
  ev: {
    calculate: (f) => f.transport > 0 ? f.transport * 0.5 : 0, // Save 50% of transport
    msg: "Switching your primary vehicle to an Electric Vehicle (EV) could reduce your transport emissions by {savings}t per year."
  },
  solar: {
    calculate: (f) => f.energy * 0.7, // Save 70% of energy
    msg: "Installing solar panels for your home energy needs could cut your footprint by {savings}t per year."
  },
  nofly: {
    calculate: (f) => appState.hasCompletedCalc ? (EMISSION_FACTORS.transport.flights[document.getElementById('flightFreq').value] || 0) : 1.5,
    msg: "Eliminating air travel from your routine could instantly save {savings}t of CO₂ annually."
  },
  wfh: {
    calculate: (f) => f.transport > 0 ? f.transport * 0.2 : 0, // Save 20% of transport
    msg: "Working from home 3 days a week could reduce your commuting emissions by {savings}t per year."
  }
};

window.runScenario = function(type) {
  const f = appState.footprint;
  const resultBox = document.getElementById('scenarioResult');
  
  if (!appState.hasCompletedCalc) {
    setSafeHTML(resultBox, "⚠️ Please complete the Carbon Calculator first so I can give you accurate scenario projections!");
    resultBox.classList.add('visible');
    return;
  }

  const scenario = SCENARIOS[type];
  const savings = scenario.calculate(f);
  
  if (savings <= 0) {
    setSafeHTML(resultBox, "Based on your current lifestyle, this change wouldn't significantly impact your footprint (you might already be doing it!).");
  } else {
    const text = scenario.msg.replace('{savings}', `<strong>${formatNum(savings)}</strong>`);
    setSafeHTML(resultBox, `✨ ${text}`);
  }
  resultBox.classList.add('visible');
}

// Module exports for Jest testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    generateBotResponse,
    handleUserMessage,
    addChatMessage,
    showTypingIndicator,
    removeTypingIndicator,
    SCENARIOS
  };
}
